/* =============================================
   DSE-Compass — College Data
   Nashik from Farheen | Pune & Mumbai sample
   ============================================= */

const COLLEGES = [
  {
    id: 1,
    name: "K. K. Wagh Institute of Engineering Education & Research",
    shortName: "KKWEIR",
    district: "Nashik",
    type: "Private",
    naac: "A",
    fees: 450000,
    hostel: true,
    avgPackage: 5.2,
    placementPct: 85,
    cutoff: 82.0,
    branches: ["Computer Engineering", "IT", "E&TC", "Mechanical", "Electrical", "Civil", "AI & DS"],
    trend: [78.0, 80.0, 82.0],
    description: "Top private autonomous engineering college in Nashik. NAAC A, strong placements.",
    dteCode: "5121"
  },
  {
    id: 2,
    name: "MVP KBT College of Engineering",
    shortName: "KBTCOE",
    district: "Nashik",
    type: "Private",
    naac: "A++",
    fees: 340000,
    hostel: true,
    avgPackage: 3.5,
    placementPct: 70,
    cutoff: 78.0,
    branches: ["Computer Engineering", "IT", "E&TC", "Mechanical", "Electrical", "Civil", "AI & DS"],
    trend: [74.0, 76.0, 78.0],
    description: "NAAC A++ autonomous college. Good mix of core and emerging branches.",
    dteCode: "5108"
  },
  {
    id: 3,
    name: "MET Institute of Engineering, Bhujbal Knowledge City",
    shortName: "METIOE",
    district: "Nashik",
    type: "Private",
    naac: "A",
    fees: 423000,
    hostel: true,
    avgPackage: 4.0,
    placementPct: 65,
    cutoff: 76.0,
    branches: ["Computer Engineering", "IT", "AI & DS", "E&TC", "Mechanical", "Electrical", "Civil"],
    trend: [72.0, 74.0, 76.0],
    description: "Well-known private college in Adgaon, Nashik with solid infrastructure.",
    dteCode: "5151"
  },
  {
    id: 4,
    name: "Sandip Institute of Technology & Research Centre",
    shortName: "SITRC",
    district: "Nashik",
    type: "Private",
    naac: "A",
    fees: 350000,
    hostel: true,
    avgPackage: 5.5,
    placementPct: 80,
    cutoff: 79.0,
    branches: ["Computer Engineering", "IT", "E&TC", "Mechanical", "Civil", "Electrical", "AI & DS"],
    trend: [75.0, 77.0, 79.0],
    description: "Autonomous institute under Sandip Foundation. Strong placement record.",
    dteCode: "5109"
  },
  {
    id: 5,
    name: "Sandip Institute of Engineering and Management",
    shortName: "SIEM",
    district: "Nashik",
    type: "Private",
    naac: "A",
    fees: 386000,
    hostel: true,
    avgPackage: 4.5,
    placementPct: 70,
    cutoff: 74.0,
    branches: ["Computer Engineering", "IT", "E&TC", "Mechanical", "Civil", "Electrical", "AI & DS"],
    trend: [70.0, 72.0, 74.0],
    description: "Part of Sandip Foundation. Good infrastructure and industry exposure.",
    dteCode: "5331"
  },
  {
    id: 6,
    name: "SNJB College of Engineering, Chandwad",
    shortName: "SNJB",
    district: "Nashik",
    type: "Private",
    naac: "A+",
    fees: 393000,
    hostel: true,
    avgPackage: 4.2,
    placementPct: 75,
    cutoff: 77.0,
    branches: ["Computer Engineering", "AI & DS", "E&TC", "Mechanical", "Civil"],
    trend: [73.0, 75.0, 77.0],
    description: "NAAC A+ autonomous college in Chandwad, Nashik district.",
    dteCode: "5173"
  },
  {
    id: 7,
    name: "Matoshri College of Engineering & Research Centre",
    shortName: "MCOERC",
    district: "Nashik",
    type: "Private",
    naac: "B",
    fees: 300000,
    hostel: true,
    avgPackage: 3.8,
    placementPct: 72,
    cutoff: 73.0,
    branches: ["Computer Engineering", "IT", "AI & DS", "E&TC", "Mechanical", "Electrical", "Civil"],
    trend: [69.0, 71.0, 73.0],
    description: "Autonomous college near Odha, Nashik. Multiple emerging branches.",
    dteCode: "5177"
  },
  {
    id: 8,
    name: "Sir Visvesvaraya Institute of Technology",
    shortName: "SVIT",
    district: "Nashik",
    type: "Private",
    naac: "B+",
    fees: 297000,
    hostel: true,
    avgPackage: 5.0,
    placementPct: 75,
    cutoff: 75.0,
    branches: ["Computer Engineering", "IT", "Chemical", "Electronics & Computer"],
    trend: [71.0, 73.0, 75.0],
    description: "Established 1998. Located in Sinnar, Nashik. Good placement percentage.",
    dteCode: "5125"
  },
  {
    id: 9,
    name: "PVG College of Engineering, Nashik",
    shortName: "PVGCOE",
    district: "Nashik",
    type: "Private",
    naac: "A",
    fees: 258000,
    hostel: true,
    avgPackage: 4.5,
    placementPct: 68,
    cutoff: 72.0,
    branches: ["Computer Engineering", "IT", "AI & DS", "E&TC", "Mechanical"],
    trend: [68.0, 70.0, 72.0],
    description: "PVG's Nashik campus. NAAC A grade with steady placements.",
    dteCode: "5330"
  },
  {
    id: 10,
    name: "Jawahar Education Society's Institute of Technology",
    shortName: "JIT",
    district: "Nashik",
    type: "Private",
    naac: "B++",
    fees: 200000,
    hostel: true,
    avgPackage: 3.2,
    placementPct: 55,
    cutoff: 70.0,
    branches: ["Computer Engineering", "IT", "AI & DS", "Electrical", "Mechanical", "Civil"],
    trend: [66.0, 68.0, 70.0],
    description: "Affordable private college on Gangapur Road, Nashik.",
    dteCode: "5401"
  },
  {
    id: 11,
    name: "Brahma Valley College of Engineering",
    shortName: "BVCERI",
    district: "Nashik",
    type: "Private",
    naac: "A",
    fees: 331000,
    hostel: true,
    avgPackage: 2.8,
    placementPct: 40,
    cutoff: 68.0,
    branches: ["Computer Engineering", "Civil", "Electrical", "Mechanical"],
    trend: [64.0, 66.0, 68.0],
    description: "Private college in Anjaneri, Trimbak Road. NAAC A grade.",
    dteCode: "5130"
  },
  {
    id: 12,
    name: "Late G.N. Sapkal College of Engineering",
    shortName: "LGNSCOE",
    district: "Nashik",
    type: "Private",
    naac: "B",
    fees: 250000,
    hostel: true,
    avgPackage: 4.0,
    placementPct: 48,
    cutoff: 71.0,
    branches: ["Computer Engineering", "AI & DS", "Civil", "Electrical", "E&TC", "Mechanical"],
    trend: [67.0, 69.0, 71.0],
    description: "Autonomous college in Anjaneri-Wadholi area, Nashik.",
    dteCode: "5182"
  },
  {
    id: 13,
    name: "COEP Technological University",
    shortName: "COEP",
    district: "Pune",
    type: "Government",
    naac: "A++",
    fees: 110000,
    hostel: true,
    avgPackage: 12.5,
    placementPct: 95,
    cutoff: 99.0,
    branches: ["Computer Engineering", "IT", "E&TC", "Mechanical", "Electrical", "Civil"],
    trend: [98.0, 98.7, 99.0],
    description: "Premier government autonomous university in Pune. Excellent ROI.",
    dteCode: "6006"
  },
  {
    id: 14,
    name: "Pune Institute of Computer Technology",
    shortName: "PICT",
    district: "Pune",
    type: "Private",
    naac: "A+",
    fees: 120000,
    hostel: true,
    avgPackage: 10.5,
    placementPct: 92,
    cutoff: 95.5,
    branches: ["Computer Engineering", "IT", "E&TC"],
    trend: [93.5, 94.5, 95.5],
    description: "Top CS-focused private college in Pune with strong coding culture.",
    dteCode: "6271"
  },
  {
    id: 15,
    name: "Vishwakarma Institute of Technology",
    shortName: "VIT",
    district: "Pune",
    type: "Private",
    naac: "A++",
    fees: 185000,
    hostel: true,
    avgPackage: 7.5,
    placementPct: 88,
    cutoff: 93.0,
    branches: ["Computer Engineering", "IT", "E&TC", "Mechanical", "Civil", "AI & DS"],
    trend: [91.0, 92.0, 93.0],
    description: "Large autonomous campus in Pune with good industry links.",
    dteCode: "6273"
  },
  {
    id: 16,
    name: "Pimpri Chinchwad College of Engineering",
    shortName: "PCCOE",
    district: "Pune",
    type: "Private",
    naac: "A",
    fees: 165000,
    hostel: true,
    avgPackage: 6.5,
    placementPct: 85,
    cutoff: 91.5,
    branches: ["Computer Engineering", "IT", "E&TC", "Mechanical", "Civil"],
    trend: [89.5, 90.5, 91.5],
    description: "Solid mid-tier autonomous college in PCMC, Pune.",
    dteCode: "6175"
  },
  {
    id: 17,
    name: "Veermata Jijabai Technological Institute",
    shortName: "VJTI",
    district: "Mumbai",
    type: "Government",
    naac: "A+",
    fees: 85000,
    hostel: true,
    avgPackage: 13.0,
    placementPct: 94,
    cutoff: 98.8,
    branches: ["Computer Engineering", "IT", "E&TC", "Mechanical", "Electrical", "Civil"],
    trend: [97.5, 98.2, 98.8],
    description: "Premier government-aided institute in Mumbai. Best ROI in state.",
    dteCode: "3012"
  },
  {
    id: 18,
    name: "Sardar Patel Institute of Technology",
    shortName: "SPIT",
    district: "Mumbai",
    type: "Private",
    naac: "A",
    fees: 210000,
    hostel: false,
    avgPackage: 15.0,
    placementPct: 92,
    cutoff: 96.5,
    branches: ["Computer Engineering", "IT", "E&TC", "Electronics"],
    trend: [94.5, 95.5, 96.5],
    description: "Top private autonomous college in Mumbai for CS/IT packages.",
    dteCode: "3215"
  }
];

function formatFees(n) {
  if (!n) return "N/A";
  if (n >= 100000) return "₹" + (n / 100000).toFixed(2) + "L";
  return "₹" + Math.round(n / 1000) + "k";
}

function typeBadgeClass(type) {
  if (type === "Government") return "badge-govt";
  if (type === "Aided") return "badge-aided";
  return "badge-private";
}
